# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import math
import time
import numpy
import src_CFTM.Func_Geometry
import src_CFTM.Func_Camera
import src_CFTM.Func_Transform
import src_CFTM.Func_Match
import src_CFTM.Func_Track
import src_CFTM.Func_Files
import src_CFTM.Func_CommonTiePoints

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

